name: iOS Build and Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1. Checkout your code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Setup Xcode 17 (via maxim-lobanov/setup-xcode)
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '17.0'

      # 3. Build & Test in the iPhone 14 simulator on the latest iOS
      - name: Build and Test
        run: |
          xcodebuild \
            -project TimeBox.xcodeproj \
            -scheme TimeBox \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14' \
            clean test